version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ResourciaFrontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "nuget"
    directory: "/ResourciaBackend/src"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
