name: resourcia
services:
  resourcia.api:
    image: ${DOCKER_REGISTRY-}resourciaapi
    build:
      context: .
      dockerfile: Resourcia.Api/Dockerfile
    env_file:
      - ../../.env
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5000
      - REDIS_URL=redis://resourcia.redis:6379
    depends_on:
      - resourcia.db
      - resourcia.redis

  resourcia.frontend:
    image: ${DOCKER_REGISTRY-}resourciafrontend
    build:
      context: ../../ResourciaFrontend
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: production
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - resourcia.api

  resourcia.db:
    image: postgres:17
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/resourcia-db:/var/lib/postgresql/data

  resourcia.redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./.containers/resourcia-redis:/data

networks:
  default:
    name: resourcia.local
