services:
  resourcia.api:
    image: ${DOCKER_REGISTRY-}resourciaapi
    build:
      context: .
      dockerfile: Resourcia.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - REDIS_URL=redis://resourcia.redis:6379
    depends_on:
      - resourcia.db
      - resourcia.redis

  resourcia.frontend:
    image: ${DOCKER_REGISTRY-}resourciafrontend
    build:
      context: ../../ResourciaFrontend
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: development
    ports:
      - "4200:80"
    depends_on:
      - resourcia.api

  resourcia.db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/resourcia-db:/var/lib/postgresql/data

  resourcia.redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./.containers/resourcia-redis:/data

networks:
  default:
    name: resourcia.local
